server:
  port: 8888
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411 # Zipkin服务器的地址
  sleuth:
    sampler:
      probability: 1.0 # 设置采样率，1.0表示全部采样
eureka:
  client:
    defaultZone: http://localhost:8761/eureka/