server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server,故不进行注册
    registerWithEureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/